-- 1. Delete from tables with foreign keys (child tables)
DELETE FROM PAYMENT;
DELETE FROM INQUIRY;
DELETE FROM BORROWED;
DELETE FROM REVIEW;
DELETE FROM CATALOGS;
DELETE FROM WRITTENBY;
DELETE FROM WITHPROMO;
DELETE FROM GUEST;
DELETE FROM PHONE;

-- 2. Delete from independent/reference tables
DELETE FROM BOOK;
DELETE FROM AUTHOR;
DELETE FROM PUBLISHER;
DELETE FROM PROMO;

-- 3. Delete from relationship tables (after removing foreign key references)
DELETE FROM LIBCARD;
-- Delete EMPLOYEE before TRAINER to avoid trigger constraint violation
-- (TRAINER deletion would set TrainedByID to NULL, but trigger requires Receptionists to have a trainer)
DELETE FROM EMPLOYEE;
DELETE FROM TRAINER;
DELETE FROM MEMBER;

-- 4. Delete from parent table (last)
DELETE FROM PERSON;

-- Verify deletion (optional - uncomment to check)
-- SELECT 'PAYMENT' AS table_name, COUNT(*) AS row_count FROM PAYMENT
-- UNION ALL SELECT 'INQUIRY', COUNT(*) FROM INQUIRY
-- UNION ALL SELECT 'BORROWED', COUNT(*) FROM BORROWED
-- UNION ALL SELECT 'REVIEW', COUNT(*) FROM REVIEW
-- UNION ALL SELECT 'CATALOGS', COUNT(*) FROM CATALOGS
-- UNION ALL SELECT 'WRITTENBY', COUNT(*) FROM WRITTENBY
-- UNION ALL SELECT 'WITHPROMO', COUNT(*) FROM WITHPROMO
-- UNION ALL SELECT 'GUEST', COUNT(*) FROM GUEST
-- UNION ALL SELECT 'PHONE', COUNT(*) FROM PHONE
-- UNION ALL SELECT 'BOOK', COUNT(*) FROM BOOK
-- UNION ALL SELECT 'AUTHOR', COUNT(*) FROM AUTHOR
-- UNION ALL SELECT 'PUBLISHER', COUNT(*) FROM PUBLISHER
-- UNION ALL SELECT 'PROMO', COUNT(*) FROM PROMO
-- UNION ALL SELECT 'LIBCARD', COUNT(*) FROM LIBCARD
-- UNION ALL SELECT 'TRAINER', COUNT(*) FROM TRAINER
-- UNION ALL SELECT 'EMPLOYEE', COUNT(*) FROM EMPLOYEE
-- UNION ALL SELECT 'MEMBER', COUNT(*) FROM MEMBER
-- UNION ALL SELECT 'PERSON', COUNT(*) FROM PERSON;

